install.packages('geojsonio')
install.packages('leaflet')
install.packages('raster')
install.packages('rgdal')
install.packages('sf')
install.packages('ncdf4')
install.packages('fields')
install.packages('knitr')
